# Generated by Django 4.1.5 on 2023-01-16 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Mobile number must be 10 digits starting with '05'.", regex='^05\\d{8}$')], verbose_name='Mobile Number'),
        ),
    ]
