# Generated by Django 4.1.5 on 2023-01-30 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_sorter_judgers_filtering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtering',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='filtering', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='judgers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='judgers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sorter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sorters', to=settings.AUTH_USER_MODEL),
        ),
    ]
