# Generated by Django 4.1.5 on 2023-01-22 12:28

import core.utility
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('hidden', models.BooleanField(blank=True, default=False, null=True)),
                ('participation_title', models.CharField(max_length=255)),
                ('participation_file', models.FileField(blank=True, max_length=2048, null=True, upload_to=core.utility.PathAndRename('uploads/participation_file/2023/01/22'))),
                ('work_overview', models.CharField(max_length=255)),
                ('year_of_execution', models.CharField(max_length=255)),
                ('work_publishing', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=1)),
                ('profitable_projects', models.IntegerField(default=0)),
                ('score', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('application_stage', models.IntegerField(choices=[(0, 'Filteration'), (1, 'Judgement')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateSubApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('hidden', models.BooleanField(blank=True, default=False, null=True)),
                ('stander_questions', models.JSONField(default=list)),
                ('score_per_phase', models.FloatField(blank=True, default=0, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates_tracks', to='candidate.candidateapplication')),
                ('phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.phase')),
                ('pillar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.pillar')),
                ('pillar_stander', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.pallarstander')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('hidden', models.BooleanField(blank=True, default=False, null=True)),
                ('national_id', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='ID number must be 10 digits.', regex='\\d{10}$')])),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('is_saudi', models.BooleanField(default=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('age_range', models.CharField(blank=True, max_length=255, null=True)),
                ('regdate', models.DateField()),
                ('initiative_know', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(choices=[(201, 'Approved'), (403, 'Blocked')], default=201)),
                ('cv', models.FileField(blank=True, max_length=2048, null=True, upload_to=core.utility.PathAndRename('uploads/cv/2023/01/22'))),
                ('picture_id', models.FileField(blank=True, max_length=2048, null=True, upload_to=core.utility.PathAndRename('uploads/picture_id/2023/01/22'))),
                ('previous_work_upload', models.FileField(blank=True, max_length=2048, null=True, upload_to=core.utility.PathAndRename('uploads/participation_file/2023/01/22'))),
                ('support', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=1)),
                ('support_details', models.TextField(blank=True, null=True)),
                ('previous_activities', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=1)),
                ('previous_activities_yes', models.TextField(blank=True, null=True)),
                ('snapchat_url', models.URLField(blank=True, null=True)),
                ('instagram_media_url', models.URLField(blank=True, null=True)),
                ('youtube_media_url', models.URLField(blank=True, null=True)),
                ('linked_media_url', models.URLField(blank=True, null=True)),
                ('twitter_media_url', models.URLField(blank=True, null=True)),
                ('other_media_url', models.URLField(blank=True, null=True)),
                ('inspiration_story', models.TextField(blank=True, null=True)),
                ('additional_files', models.TextField(blank=True, null=True)),
                ('honors_upload', models.FileField(blank=True, max_length=2048, null=True, upload_to=core.utility.PathAndRename('uploads/honors_upload_file/2023/01/22'))),
                ('local_award', models.FileField(blank=True, max_length=2048, null=True, upload_to=core.utility.PathAndRename('uploads/local_award_file/2023/01/22'))),
                ('international_awards', models.FileField(blank=True, max_length=2048, null=True, upload_to=core.utility.PathAndRename('uploads/nternational_awards_file/2023/01/22'))),
                ('tv_host', models.CharField(blank=True, max_length=255, null=True)),
                ('press_interviews', models.CharField(blank=True, max_length=255, null=True)),
                ('training_courses', models.CharField(blank=True, max_length=255, null=True)),
                ('academic_certifications', models.CharField(blank=True, max_length=255, null=True)),
                ('volunteering', models.URLField(blank=True, null=True)),
                ('book_permit', models.URLField(blank=True, null=True)),
                ('ownership_agreement', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidate.candidateprofile'),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.tracks'),
        ),
        migrations.AlterUniqueTogether(
            name='candidateapplication',
            unique_together={('track', 'profile')},
        ),
    ]
