# Generated by Django 4.1.5 on 2023-01-18 18:42

import core.utility
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('hidden', models.BooleanField(blank=True, default=False, null=True)),
                ('national_id', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='ID number must be 10 digits.', regex='\\d{10}$')])),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('is_saudi', models.BooleanField(default=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('age_range', models.CharField(blank=True, max_length=255, null=True)),
                ('regdate', models.DateField()),
                ('initiative_know', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(choices=[(201, 'Approved'), (403, 'Blocked')], default=201)),
                ('score', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('cv', models.FileField(blank=True, max_length=2048, null=True, upload_to=core.utility.PathAndRename('uploads/cv/2023/01/18'))),
                ('picture_id', models.FileField(blank=True, max_length=2048, null=True, upload_to=core.utility.PathAndRename('uploads/picture_id/2023/01/18'))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
