# Generated by Django 4.1.5 on 2023-01-22 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatesubapplication',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.phase'),
        ),
        migrations.AlterField(
            model_name='candidatesubapplication',
            name='pillar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.pillar'),
        ),
        migrations.AlterField(
            model_name='candidatesubapplication',
            name='pillar_stander',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.pallarstander'),
        ),
    ]
