# Generated by Django 4.1.5 on 2023-02-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='status',
            field=models.IntegerField(choices=[(1, 'Approved'), (0, 'Blocked')], default=0),
        ),
    ]
