# Generated by Django 4.1.5 on 2023-01-18 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='district',
            new_name='region',
        ),
    ]
