# Generated by Django 4.1.5 on 2023-01-18 20:22

import core.utility
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('candidate', '0002_rename_district_candidateprofile_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='academic_certifications',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='additional_files',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='book_permit',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='honors_upload',
            field=models.FileField(blank=True, max_length=2048, null=True, upload_to=core.utility.PathAndRename('uploads/honors_upload_file/2023/01/18')),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='inspiration_story',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='instagram_media_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='international_awards',
            field=models.FileField(blank=True, max_length=2048, null=True, upload_to=core.utility.PathAndRename('uploads/nternational_awards_file/2023/01/18')),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='linked_media_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='local_award',
            field=models.FileField(blank=True, max_length=2048, null=True, upload_to=core.utility.PathAndRename('uploads/local_award_file/2023/01/18')),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='other_media_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='ownership_agreement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='press_interviews',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='previous_activities',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=1),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='previous_activities_yes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='previous_work_upload',
            field=models.FileField(blank=True, max_length=2048, null=True, upload_to=core.utility.PathAndRename('uploads/participation_file/2023/01/18')),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='snapchat_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='support',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=1),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='support_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='training_courses',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='tv_host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='twitter_media_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='volunteering',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='youtube_media_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CandidateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('hidden', models.BooleanField(blank=True, default=False, null=True)),
                ('participation_title', models.CharField(max_length=255)),
                ('participation_file', models.FileField(blank=True, max_length=2048, null=True, upload_to=core.utility.PathAndRename('uploads/participation_file/2023/01/18'))),
                ('work_overview', models.CharField(max_length=255)),
                ('year_of_execution', models.CharField(max_length=255)),
                ('work_publishing', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=1)),
                ('profitable_projects', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidateprofile')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.tracks')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
