# Generated by Django 4.1.5 on 2023-01-22 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_rename_stander_questions_candidatesubapplication_submitted_stander_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatesubapplication',
            old_name='submitted_stander_questions',
            new_name='questions',
        ),
    ]
