# Generated by Django 4.1.5 on 2023-01-28 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_alter_candidatestanders_candidate_pillar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatepillarsubapplication',
            name='sub_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates_sub_application', to='candidate.candidatesubapplication'),
        ),
        migrations.AlterField(
            model_name='candidatestanders',
            name='candidate_pillar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates_pillar', to='candidate.candidatepillarsubapplication'),
        ),
    ]
