# Generated by Django 4.1.5 on 2023-01-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_rename_submitted_stander_questions_candidatesubapplication_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatesubapplication',
            old_name='score_per_phase',
            new_name='score_per_pillar',
        ),
    ]
