# Generated by Django 4.1.5 on 2023-01-28 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_alter_candidatepillarsubapplication_sub_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateapplication',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='candidate.candidateprofile'),
        ),
        migrations.AlterField(
            model_name='candidatesubapplication',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates_application', to='candidate.candidateapplication'),
        ),
    ]
