# Generated by Django 4.1.5 on 2023-01-22 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0005_rename_score_per_phase_candidatesubapplication_score_per_pillar'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatesubapplication',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
