# Generated by Django 4.1.5 on 2023-01-23 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('candidate', '0006_candidatesubapplication_reviewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatesubapplication',
            name='pillar',
        ),
        migrations.RemoveField(
            model_name='candidatesubapplication',
            name='pillar_stander',
        ),
        migrations.RemoveField(
            model_name='candidatesubapplication',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='candidatesubapplication',
            name='score_per_pillar',
        ),
        migrations.AddField(
            model_name='candidatesubapplication',
            name='phase_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='candidateapplication',
            name='participation_file',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='cv',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='honors_upload',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='international_awards',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='local_award',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='picture_id',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='previous_work_upload',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CandidatePillarSubApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('hidden', models.BooleanField(blank=True, default=False, null=True)),
                ('capture_questions_answers', models.JSONField(default=list)),
                ('score_per_pillar', models.FloatField(default=0)),
                ('pillar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.pillar')),
                ('pillar_stander', models.ManyToManyField(to='crm.pallarstander')),
                ('sub_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidatesubapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
