# Generated by Django 4.1.5 on 2023-01-26 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PallarStander',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('hidden', models.BooleanField(blank=True, default=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('pillarStanderQuestions', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('hidden', models.BooleanField(blank=True, default=False, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('hidden', models.BooleanField(blank=True, default=False, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('hidden', models.BooleanField(blank=True, default=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('questions', models.JSONField(default=list)),
                ('tracks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks_screening', to='crm.tracks')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('hidden', models.BooleanField(blank=True, default=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('weight', models.IntegerField(default=0)),
                ('pallarStander', models.ManyToManyField(blank=True, related_name='list_of_pallarStander', to='crm.pallarstander')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='crm.phase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='phase',
            name='tracks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='crm.tracks'),
        ),
    ]
