# Generated by Django 4.1.5 on 2023-01-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='questions',
            field=models.JSONField(),
        ),
    ]
