# Generated by Django 4.1.5 on 2023-01-31 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallarstander',
            name='pillar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pillar', to='crm.pillar'),
        ),
    ]
